name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.16.x, 1.19.x, 1.20.x ]
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: |
        go test -v ./...

    - name: Coverage Dependencies
      if: matrix.go == '1.16.x'
      run: |
        go install github.com/mattn/goveralls@latest

    - name: Coverage Reporting Generation
      if: matrix.go == '1.16.x'
      run: |
        export PKGS=$(go list ./... | grep -vE "(gotests/gotests|.*data|templates)" | tr -s '\n' ',' | sed 's/.\{1\}$//')
        go test -v -covermode=count -coverpkg=$PKGS -coverprofile=coverage.cov

    - name: Coverage - Sending Report to Coveral
      if: matrix.go == '1.16.x'
      run: goveralls -coverprofile=coverage.cov -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
